# Generated by Django 6.0.3 on 2026-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_advertisement_emailotp_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_credits',
            field=models.IntegerField(default=0, verbose_name='Кредиты для ИИ'),
        ),
    ]
